# Generated by Django 5.1.5 on 2025-02-28 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='HeroQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.JSONField()),
                ('marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.streams')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.topics')),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(default=0)),
                ('test_type', models.CharField(choices=[('CUSTOM', 'custom'), ('MOCK', 'mock')], default='custom', max_length=6)),
                ('subjects_included', models.JSONField(default=list)),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.streams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultQuestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.userresult')),
            ],
        ),
    ]
