# Generated by Django 5.1.5 on 2025-03-13 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResult',
            new_name='TestHistory',
        ),
        migrations.RemoveField(
            model_name='heroquestions',
            name='answer',
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.JSONField(),
        ),
    ]
