# Generated by Django 5.1.5 on 2025-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_chapters_chapter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='chapter_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='streams',
            name='stream_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
