# Generated by Django 5.1.5 on 2025-03-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_generatedtestpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtestpaper',
            name='questions',
        ),
        migrations.AddField(
            model_name='generatedtestpaper',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.heroquestions'),
        ),
    ]
