# Generated by Django 5.1.5 on 2025-03-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_generatedtestpaper_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtestpaper',
            name='questions',
        ),
        migrations.AlterField(
            model_name='generatedtestpaper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TestQuestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.heroquestions')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.generatedtestpaper')),
            ],
        ),
    ]
