# Generated by Django 5.1.5 on 2025-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_generatedtestpaper_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtestpaper',
            name='subjects_included',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='generatedtestpaper',
            name='test_type',
            field=models.CharField(choices=[('CUSTOM', 'custom'), ('MOCK', 'mock')], default='custom', max_length=6),
        ),
    ]
