# Generated by Django 5.1.5 on 2025-04-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_generatedtestpaper_subjects_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.topics'),
        ),
        migrations.AddField(
            model_name='resultquestionlink',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultquestionlink',
            name='total_marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='questions.subjects'),
        ),
        migrations.AlterField(
            model_name='heroquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_instances', to='questions.questions'),
        ),
        migrations.AlterField(
            model_name='resultquestionlink',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='questions.testhistory'),
        ),
        migrations.AlterField(
            model_name='resultquestionlink',
            name='user_answer',
            field=models.JSONField(),
        ),
    ]
