# Generated by Django 5.1.5 on 2025-05-24 00:10

from django.db import migrations

CONSTRAINT_NAME = "questions_heroquesti_question_id_78f5c395_fk_questions"
TABLE_NAME = "questions_heroquestions"  # The table with the foreign key
COLUMN_NAME = "question_id"
REFERENCED_TABLE_NAME = "questions_questions" # The table the FK points to

class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0007_questions_topic_resultquestionlink_marks_obtained_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql=f"""
                ALTER TABLE {TABLE_NAME}
                DROP CONSTRAINT IF EXISTS {CONSTRAINT_NAME};
                ALTER TABLE {TABLE_NAME}
                ADD CONSTRAINT {CONSTRAINT_NAME}
                    FOREIGN KEY ({COLUMN_NAME})
                    REFERENCES {REFERENCED_TABLE_NAME}(id)
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=f"""
                ALTER TABLE {TABLE_NAME}
                DROP CONSTRAINT IF EXISTS {CONSTRAINT_NAME};
                ALTER TABLE {TABLE_NAME}
                ADD CONSTRAINT {CONSTRAINT_NAME}
                    FOREIGN KEY ({COLUMN_NAME})
                    REFERENCES {REFERENCED_TABLE_NAME}(id) DEFERRABLE INITIALLY DEFERRED;
                -- ^ This reverse SQL puts it back to how it was (without ON DELETE CASCADE)
            """
        ),
    ]
